### ISSUE TITLE
Wrongly positioned steam source for tank engines running cab ahead

### ISSUE THREAD

**Issue by auge8472** [GarlicBread42/GETS#1]
When tank engines running cab ahead the source of the steam is the cab and not the chimney.

![screenshot of a tank engine running cab ahead with steam coming from the cabin](https://user-images.githubusercontent.com/1734660/200039432-b36cef22-cc35-4299-a30e-8bff11d457cc.png)

The NML-spec says on the page [Vehicles, section train properties](https://newgrf-specs.tt-wiki.net/wiki/NML:Vehicles#Train_properties), that there is the property `visual_effect_and_powered`, which provides the possibility to set an offset for the effects. Looks, like this seems to be the way to go.

**Comment by GarlicBread42** [comment]
Dear Heiko,

thanks for the report. Bug has been fixed and will be in the next release.

Cheers!

Heiko August ***@***.***> schrieb am Fr., 4. Nov. 2022, 18:40:
