### ISSUE TITLE
Invisible BR 112 in version 0.4

### ISSUE THREAD

**Issue by auge8472** [GarlicBread42/GETS#2]
Installed version 0.4 a few days ago and started a game in the 1990-ies to see the newly introduced BR 112. But, exactly this is a problem. I can see the locomotive type in the purchase menu but, if bought, the machine is invisible. It is invisible in its details windows, it's invisible in the depot, station or waypoint lists, it's invisible on tracks. A train with such an invisible locomotive actually works but the waggons run magically with no visible locomotive in front of the train.

You see in the screenshot two locomotives, bought a few game seconds ago. Train 1 is an invisible BR 112, the train 2 (for comparision) is a BR 111 which is visible in all game windows and on tracks.

![Screenshot of the statistics of two new locomotives, one of them is invisible in all game windows](https://github.com/GarlicBread42/GETS/assets/1734660/9afe35b1-9cb6-496e-9171-0e63d678660c)

**Comment by GarlicBread42** [comment]
Issue solved by changing line 125 of src/ELECTRIC/BR_112.pnml to correct value. (was: ITEM_BR_111_BUILD - is now: ITEM_BR_112_BUILD)

Until the next release you can use the other variants, they're working correctly.

Thanks for reporting!
